server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useSSL=false
    username: mariadb
    password: mariadb
    driver-class-name: com.mysql.cj.jdbc.Driver